# Generated by Django 5.1.6 on 2025-03-24 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_customer', models.CharField(max_length=20)),
                ('cin', models.CharField(max_length=10)),
                ('adress_customer', models.CharField(max_length=200)),
                ('adress_recipient', models.CharField(max_length=200)),
                ('nature_of_package', models.CharField(max_length=100)),
                ('number_phone_customer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Statues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statue', models.IntegerField(choices=[('', 'processing'), ('', 'out for delivery'), ('', 'completed')])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.order')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
