# Generated by Django 5.1.6 on 2025-04-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='statues',
            name='statue',
            field=models.IntegerField(choices=[(1, 'processing'), (2, 'out for delivery'), (3, 'completed')]),
        ),
    ]
