# Generated by Django 5.1.6 on 2025-04-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_login_alter_statues_statue'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
