# Generated by Django 5.1.6 on 2025-04-05 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_usermodel_alter_statues_user_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statues',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='delivery.usermodel'),
        ),
    ]
